name: Check script syntax

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-26.04
    steps:
      -name: Checkout repository
       uses: actions/checkout@4
      -name: Check bash script syntax
        run: |
          for sh in "*.sh"; do
            echo "Checking script $sh"
            bash -n "$sh"
          done
